#ifndef _BOARD_H
#define _BOARD_H

#define PIN_SCL 2
#define PIN_SDA 3

#define I2C_MASTER_FREQ_HZ    100000
#define I2C_MASTER_NUM        0
#define I2C_MASTER_TIMEOUT_MS 1000

#define EVENT_QUEUE_DAYS 2
#define EVENT_QUEUE_MAX_SENSORS 3
#define EVENT_QUEUE_MAX_EVENTS_PER_DAY (12 * 24)
#define EVENT_QUEUE_MAX_EVENTS_PER_MESSAGE 12
#define EVENT_QUEUE_MAX_CLIENTS 3

#endif
