#ifndef EVENTS_TEST_BOARD_H
#define EVENTS_TEST_BOARD_H

#define EVENT_QUEUE_DAYS 2
#define EVENT_QUEUE_MAX_SENSORS 3
#define EVENT_QUEUE_MAX_EVENTS_PER_DAY (12 * 24)
#define EVENT_QUEUE_MAX_EVENTS_PER_MESSAGE 12
#define EVENT_QUEUE_MAX_CLIENTS 3

#endif
